name: Compile app
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
env:
  JAVA_VERSION: 21
  IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}

jobs:
  Comipile_APP:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'gradle'

      - name: gradlew
        run: |
          chmod 777 ./gradlew 
          ./gradlew build
          cp build/libs/*.jar .

      - name: release modification
        if: env.IS_TAG == 'true'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.jar"